/*
 * LIMES Core Library - LIMES – Link Discovery Framework for Metric Spaces.
 * Copyright © 2011 Data Science Group (DICE) (ngonga@uni-paderborn.de)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.aksw.limes.core.measures.mapper.topology.cobalt.area;

import org.aksw.limes.core.io.cache.ACache;
import org.aksw.limes.core.io.cache.MemoryCache;
import org.aksw.limes.core.io.mapping.AMapping;
import org.aksw.limes.core.io.mapping.MappingFactory;
import org.aksw.limes.core.measures.mapper.AMapper;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class CobaltAreaWithinMapperTest {

    @Test
    public void testGetMapping() {
        ACache s = new MemoryCache();
        s.addTriple("http://test.com/s/#1", "asWKT", "POLYGON ((-8 -8, 2 8, 8 8, 8 2, -8 -8))");
        s.addTriple("http://test.com/s/#2", "asWKT", "POLYGON ((-10 -10, 0 10, 10 10, 10 0, -10 -10))");
        ACache t = new MemoryCache();
        t.addTriple("http://test.com/t/#1", "asWKT", "POLYGON ((-10 -10, 0 10, 10 10, 10 0, -10 -10))");
        t.addTriple("http://test.com/t/#2", "asWKT", "POLYGON ((-20 -20, -10 0, 0 0, 0 -10, -20 -20))");
        AMapping referenceMapping = MappingFactory.createMapping(MappingFactory.MappingType.MEMORY_MAPPING);
        referenceMapping.add("http://test.com/s/#1", "http://test.com/t/#1", 1.0d);
        referenceMapping.add("http://test.com/s/#2", "http://test.com/t/#1", 1.0d);
        AMapper mapper = new CobaltAreaWithinMapper();
        assertEquals("Expect mapping generated by CobaltAreaWithinMapper to be equal to reference mapping",
                mapper.getMapping(s, t, "?x", "?y", "top_cobalt_area_within(x.asWKT, y.asWKT)", 1.0d), referenceMapping);
    }

}