package org.aksw.limes.core.ml.algorithm;

import java.util.List;

import org.aksw.limes.core.exceptions.NoSuchParameterException;
import org.aksw.limes.core.io.cache.Cache;
import org.aksw.limes.core.io.mapping.AMapping;
import org.aksw.limes.core.ml.setting.LearningParameter;

/**
 * @author Tommaso Soru (tsoru@informatik.uni-leipzig.de)
 *
 */
public abstract class AMLAlgorithm {

    private ACoreMLAlgorithm ml;

    /**
     * @return the ML algorithm name
     */
    public String getName() {
        return getMl().getName();
    }
    
    /**
     * @return the associated Core ML algorithm 
     */
    public ACoreMLAlgorithm getMl() {
        return ml;
    }


    /**
     * Initialize the ML Algorithm.
     * 
     * @param lp learning parameters
     * @param sourceCache the source cache
     * @param targetCache the target cache
     */
    public void init(List<LearningParameter> lp, Cache source, Cache target) {
        getMl().init(lp, source, target);
    }

    /**
     * Predict new links.
     * 
     * @param source the source cache
     * @param target the target cache
     * @param mlModel the ML model generated by the learning phase
     * @return the predicted mapping
     */
    public AMapping predict(Cache source, Cache target, MLResults mlModel) {
        return getMl().predict(source, target, mlModel);
    }

    /**
     * @return the ML algorithm as supervised-learning algorithm 
     */
    public SupervisedMLAlgorithm asSupervised() {
        return (SupervisedMLAlgorithm) this;
    }

    /**
     * @return the ML algorithm as unsupervised-learning algorithm 
     */
    public UnsupervisedMLAlgorithm asUnsupervised() {
        return (UnsupervisedMLAlgorithm) this;
    }

    /**
     * @return the ML algorithm as active-learning algorithm 
     */
    public ActiveMLAlgorithm asActive() {
        return (ActiveMLAlgorithm) this;
    }

    /**
     * @return the learning parameters
     */
    public List<LearningParameter> getParameters() {
        return getMl().getParameters();
    }

    /**
     * @param ml the core ML algorithm
     */
    public void setMl(ACoreMLAlgorithm ml) {
        this.ml = ml;
    }

	/**
	 * @param par parameter name
	 * @param val parameter value
	 */
	public void setParameter(String par, Object val) {
        for(LearningParameter lp : getParameters())
        	if(lp.getName().equals(par)) {
        		lp.setValue(val);
        		return;
        	}
        // if not found
        throw new NoSuchParameterException(par);
	}

}
