package org.aksw.limes.core.datastrutures;

public enum LogicOperator {
	AND, OR, MINUS, DIFF, XOR, LUKASIEWICZT, LUKASIEWICZTCO, LUKASIEWICZDIFF, ALGEBRAICT, ALGEBRAICTCO, ALGEBRAICDIFF, EINSTEINT, EINSTEINTCO, EINSTEINDIFF, HAMACHERT, HAMACHERTCO, HAMACHERDIFF
}
